### ISSUE TITLE
Lost menu items on QA administrator

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#123]
It seems the menu items for "content," "menus," and "extensions" went missing in the administrator on QA. 
<img width="574" alt="screen shot 2018-02-28 at 9 01 58 pm" src="https://user-images.githubusercontent.com/21963909/36825046-0f333fc0-1ccb-11e8-8a58-86876fa4c6b5.png">

**Comment by mdlama** [comment]
That's weird.  Are you still having that problem, Jenny?  I see the normal menu below.  Let me try some other browsers and see what happens.

<img width="677" alt="screen shot 2018-03-01 at 9 14 42 am" src="https://user-images.githubusercontent.com/4877315/36849061-0a85c36a-1d31-11e8-8615-e690cf7745e9.png">

**Comment by mdlama** [comment]
Oh, try it again - I think I know what happened.  I gave you publisher status thinking that was why you couldn't create an article page.

**Comment by trisketz** [comment]
They are back, thank you!
