### ISSUE TITLE
Icons not showing in site-wide publication macro 

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#134]
Hi, @trisketz !  It looks like icons are not showing up when I try the macro in a regular group:

https://dev.qubeshub.org/groups/teamqubes/sandbox/generalinfo

<img width="1065" alt="screen shot 2018-03-23 at 6 34 42 am" src="https://user-images.githubusercontent.com/4877315/37824848-5562f616-2e64-11e8-9fc1-ba99c4e4b082.png">

Can you take a look?  Thanks!

**Comment by trisketz** [comment]
Ah, I failed to realize that font awesome isn't available across the whole site. I'll go ahead and make changes to the php and css to use Hubzero's fontcons instead. Sorry about that!

**Comment by trisketz** [comment]
Ok, so.. little snag. Hubzero doesn't really have a forking icon like we used. They do that this one though: 
<img width="96" alt="screen shot 2018-03-23 at 11 38 16 am" src="https://user-images.githubusercontent.com/21963909/37842012-07713938-2e8f-11e8-997d-b24f3da843a1.png">

We can switch to that one. Unless we want to add Font Awesome to the site? (My favorite choice, ha! :D )

**Comment by mdlama** [comment]
Hmmm, they must have it as they use it on their forking button on a publication view, e.g.

https://qubeshub.org/publications/414/1

Maybe we can replicate what they're doing?

**Comment by trisketz** [comment]
Interesting, they didn't list it on their fontcons documentation. I'll take a look.

**Comment by trisketz** [comment]
Alright, I really am awake -.- I also realized that I had used the icon before on the publication record mock up. Anyways, I got it fixed. You should be seeing the icons now. I committed the changes.

**Comment by mdlama** [comment]
Sweet, thanks, Jenny!  Don't worry - I got woken up at 3:30 this morning and am on about 1/8 brainpower.  And I'm still coding!  Danger!! :)
