### ISSUE TITLE
PHP pages in super groups not showing up?

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#139]
I noticed for BIOMAAP and Data Nuggets, any php pages created on the backend are now no longer showing up on their super group site. Most notably on BIOMAAP since almost all their pages I created on the backend under /pages in their super group directory. 

Data Nuggets, the only php page not showing up is the overview.php page, which overwrites their original overview page that had prior. Both BIOMAAP and Data Nuggets overview pages are reverting back to their original state, before I had created the overview.php.

All groups with pages that I had cut and copied html into the CK Editor on the front end are fine.

**Comment by mdlama** [comment]
Thanks, Jenny.  Just submitted a support ticket.  I'll cc you on it.  Good (well, not good I guess) find!

**Comment by mdlama** [comment]
I've disabled the plugin while we figure out what is going on.

https://qubeshub.org/support/ticket/1102

**Comment by mdlama** [comment]
Fixed!
