### ISSUE TITLE
Ambassadors page looks a bit wonky

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#143]
Hi, Jenny!  Ambassadors page looks a bit wonky.  Can you please take a look?  Thanks!

https://qubeshub.org/community/fmns/ambassadors

<img width="1440" alt="screen shot 2018-04-10 at 2 56 36 pm" src="https://user-images.githubusercontent.com/4877315/38577623-75efb134-3ccf-11e8-9f22-277f6c6ff9d6.png">

**Comment by trisketz** [comment]
Got it fixed! \o

**Comment by mdlama** [comment]
Awesome, thanks, Jenny!
