### ISSUE TITLE
Weird stuff with showcase and following picture in /news

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#147]
![logo_niser_square](https://user-images.githubusercontent.com/4877315/39279811-6177dadc-48c9-11e8-9fb6-1412733decbf.png)
<img width="1140" alt="screen shot 2018-04-25 at 8 43 29 pm" src="https://user-images.githubusercontent.com/4877315/39279812-633b1816-48c9-11e8-8472-da0ee24596ab.png">

**Comment by mdlama** [comment]
I changed it back to the original image cuz it was too crazy!

**Comment by mdlama** [comment]
Hey, Jenny.  Did you get a chance to take a look at this?

**Comment by trisketz** [comment]
News & Activities page has since been updated and is behaving. Although the showcase module is not pulling in images on two of the QUBES newsletters. 
![screen shot 2019-02-27 at 8 52 38 pm](https://user-images.githubusercontent.com/21963909/53538061-ca698680-3ad1-11e9-9dcf-8c5b6dcac892.png)
