### ISSUE TITLE
Add user name to mini dashboard in place of ALL CATEGORIES

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#189]
I think it's useful to have the user's name in the mini-dashboard (like the previous one).  Maybe this is just a problem for the leadership team with multiple accounts.  Another idea would be to add their username in smaller font right under their name.  This is not needed in many places, but if people want to submit tools, there is no other place that I know to find this information (maybe in the profile?)

Open for discussion on this one.

**Comment by trisketz** [comment]
I feel like it won't hurt to have the user's name or username. But I would pick one, either username or the user's name and not have both. That would be my preference at least.

**Comment by mdlama** [comment]
Sounds good.  Let’s go with the user’s name.  

- Drew

**Comment by mdlama** [comment]
Commit #196
