### ISSUE TITLE
Get HTML/CSS for group publication plugin mockup

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#209]
Mockup: https://drive.google.com/file/d/1yF3hlS-qnXu8zKEuSEjefA6Pj4Pa5mid/view

**Comment by trisketz** [comment]
[resources_plugin.zip](https://github.com/qubeshub/hubzero-cms/files/3317284/resources_plugin.zip)
Here it is. If you need me to compile the sass file, let me know. Couple of changes I made vs the mockup:
- Sort by is no longer a dropdown, but instead all displayed horizontally (a lot like how it is on Forums). I did this to reduce number of clicks.
- Under the filtering options. I didn't make "Type" and "Tags"sections accordions. I'm on the fence if hiding those sections is needed.

**Comment by trisketz** [comment]
Please ignore the previous files. Here is the updated files which includes markup for list views.
[resource_plugin_updated.zip](https://github.com/qubeshub/hubzero-cms/files/3323007/resource_plugin_updated.zip)

Note: I did not code up the toggling of images in the list view. I felt that if I did, it would most likely be handled very differently when Bharath actually went to implement it. I also did not code up switching between card and list views.

**Comment by mdlama** [comment]
I think not toggling images is fine for now.  @BharathR8, let us know if you need anything else, and thanks Jenny!

**Comment by BharathR8** [comment]
Hi Drew,

That’s not a problem. Will get back to you if I need anything. And thanks
for sending it Jenny.

Regards,
Bharath Chandra Reddy Barakam
