### ISSUE TITLE
Get mockup for list view in publications macro

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#210]

**Comment by trisketz** [comment]
[https://drive.google.com/drive/u/0/folders/0B2MW3q8kqpJycF9jNWhvUDdodFk](url)

**Comment by mdlama** [comment]
Thanks, Jenny!  Hey, @BharathR8 , check out the link Jenny gave above.  Jenny, can we get the prototype as well?

**Comment by trisketz** [comment]
I updated the resource plugin files to include the markup and files for list views. Please see: [Issue 209](https://github.com/qubeshub/hubzero-cms/issues/209) for the updated files.
