### ISSUE TITLE
header.less updates not showing up

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#226]
![Screen Shot 2019-10-01 at 4 19 07 PM](https://user-images.githubusercontent.com/21963909/66004919-398fca80-e467-11e9-97b5-794cd18ce693.png)

Not sure if I did something wrong with the last pull request #225. But styling updates are not showing up, despite them being in the less files. It's working on my vagrant however. A compiling issue maybe?

**Comment by mdlama** [comment]
No, nothing you did.  Problem is on HubZero side.  Usually I have to “flip a switch” on the backend from production to development, which forces the Hub to recompile all less files.  Unfortunately that isn’t working at the moment.  I’ve got a support ticket in on this.  I’ll ping them again and cc you on that ticket.

**Comment by trisketz** [comment]
Cool, thanks for letting me know! :)
