### ISSUE TITLE
Can we override /resources to not point to com_resources?

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#24]
Should work here to override the resources page:  

`/app/templates/bmc/html/com_resources/intro/default.php`

**Comment by mdlama** [comment]
@trisketz Hi, Jenny.  I think you should put the Resources portal page in the template location listed above.  This will allow us to use the URL https://dev.qubeshub.org/resources.  Another good thing about this is we can just create that page dynamically and not have to create separate modules for the resources (although maybe we still want to do that - not sure yet).

**Comment by trisketz** [comment]
@mdlama I didn't see com_resources in the /app/templates/bmc/html directory. Did you still want me to put the portal mock up here?

**Comment by mdlama** [comment]
I put the current override there, with (I'm sure) some css files in the `html/com_resources` that we won't need for long.  I think it's still a good idea to put the mock-up there.  It makes the menus work a lot easier (especially with breadcrumbs).

**Comment by trisketz** [comment]
I see it now. Not sure why I wasn't finding it last night.

**Comment by mdlama** [comment]
Sorry, I meant that I put it there this morning.  :)
