### ISSUE TITLE
Create mod_partners to show icons

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#30]

**Comment by trisketz** [comment]
Absolutely! At the time I just made a small filler grid till I had an idea of how many partners we wanted to display and how we were going to go about doing it. I'll update the css to allow it to stretch out.

**Comment by trisketz** [comment]
@mdlama I was playing with a couple of ideas. CSS grid can make the logo grid responsive. Sometimes it will cause the gaps in the columns to be wider than what I initially planned for. But this may not be a big deal since some logos have transparent backgrounds or whatnot. 

Other option is to make a fixed grid.

Note: 
1.I haven't pushed this to dev. But if it helps to look at it live, i can.
2. I replaced the image placeholders with just colored divs. 
3. The whole mock up isn't responsive yet, nor have I put in the fallback if css grid isn't supported yet. 
![grid](https://user-images.githubusercontent.com/21963909/35245940-8f1eb2c2-ff8a-11e7-858d-db9003973eb3.jpg)

**Comment by mdlama** [comment]
I like options.  :)  Let's not make a decision yet until we get some actual content in there.  I'm close, by the way!  Here's a pic of things on my vagrant box:

<img width="801" alt="screen shot 2018-01-23 at 12 48 59 pm" src="https://user-images.githubusercontent.com/4877315/35292078-6457eff0-003d-11e8-8f6b-a385bc879f23.png">

I've created a module called `mod_partners`.  The code is already merged into dev.  Can I go ahead and update the CSS to what you have on dev and we can start using the module?

**Comment by mdlama** [comment]
Alright, I believe we have a working version.  Just search for "QUBES Partners" in the Module area on the backend, and assign it to a position for the front page (like "communityLeft"), then use the following 

```
<xhub:module position="communityLeft">
```

The module dynamically creates the following code:

```
<div class="network-logos">
  <div class="logo">
  </div>
</div>
```

**Comment by mdlama** [comment]
P.S.  I need to add the "Featured" ability, i.e. add a featured flag to partners, and then code it so that only featured partners are pulled (if specified in the module configuration).  Stay tuned...

**Comment by trisketz** [comment]
Awesome! I'll give a go!

**Comment by trisketz** [comment]
Hmm.. so I'm in dev and looking under module manager, but I'm not seeing it. Am I missing it?

**Comment by mdlama** [comment]
Oops, sorry.  Try now.  I forgot to officially install it.

**Comment by trisketz** [comment]
I'm still not seeing it.

**Comment by mdlama** [comment]
Ah, sorry!  I keep leaving critical information off.  You need to add an _instance_ of the module (plus sign, upper left).  With modules, you install the module, and then you can create multiple instances (for example, one can be put on the front page, and another on a different page, with different settings and styling).  I went ahead and created an instance for the front page (it's called "Front Page Partners").  The position is set to "mainPageLeft" - you can change that.  If you want to use it as is, use this in the main page:

```
<xhub:module position="mainPageLeft">
```

Hope this works this time!

**Comment by mdlama** [comment]
I went ahead and added it.  I also realized it should be

```
{xhub:module position="mainPageLeft"}
```

One more change:  I removed the Home from the menu, so clicking on the logo now takes you back to the main page.

**Comment by trisketz** [comment]
I just took a look at the homepage on dev and I can see NSF logo there, very nice! Should I just remove the title that comes along with the module via css? I'll update the code so it won't have a background color anymore. I'll also work on sizing of the logos

**Comment by mdlama** [comment]
I went ahead and removed it - each module has a setting to show title or not so I disabled it.

Let me know if things don't change when you update the css.  Again, I've got duplicate css in the module css file (in particular, the network-logos and logo class).

**Comment by trisketz** [comment]
I think overall, we'd want to remove the background color and border from .logos from the module css. But I was able to do some overrides on the homepage to them. At the moment I reduced the width to 75px. My thinking was it would be easier to fit more logos ;) But if we want to see them better, then I can change it back to 100px. 

The logos look good. I'm not sure why the tool tip is all one size and is not adjusting to the content within it though.

**Comment by mdlama** [comment]
Hi, Jenny.  I've updated the partners component and the module.  The Partners component now allows for partners to be labeled "Featured".  The module can then be set to only show featured partners (which is what I think we should do on production).  Right now, the module on dev is showing all partners.

Regarding the icons:

- Can we center the icons vertically within each row?
- If we want to use color icons, we might need to put a white background for the grid.  Another option would be to apply an automatic filter, like transparency and then BW/greyscale.  Easiest would certainly be white backdrop.

This last point makes me think that we might want partners (well, at least featured partners) to upload more than one logo - color as well as transparent and white.

**Comment by trisketz** [comment]
I'm pretty iffy on automatic filters. I've tried them before with less than desirable results. Ideally, each logo would be colored similarly. But the only way to do that would be to manually change them to the shade we'd want them. Of course that could be me being picky ;)

1. I will go ahead and center the icons within each row.
2. Maybe simple fix for now is to go with a lighter background for that whole pane.

**Comment by mdlama** [comment]
Yeah, filters sounded unstable.  Okay, lighter background sounds like a good way to go!
