### ISSUE TITLE
Using partners component on homepage?

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#36]
Should we use the partners component on the homepage in the "Our Network" section, or force users to be redirected to the "Partners" page?

I'm wondering if using the component would be "too much going on" and would be distracting.

**Comment by mdlama** [comment]
Yes, the plan is to create a module that pulls the information from the Partners component and displays it on the front page.  This development is addressed in Issue #30.  I think what you can do is create the skeleton html/css, and then I can extricate that bit and put it in a module.
