### ISSUE TITLE
Adding css files to media manager or in the template?

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#38]
For clarification, when I add my css files for the portal pages, do I add them to the media manager (which is what I was initially thinking) or to the template>bmc>css>pages directory? Since I just realized that is what it is linking to currently.

**Comment by mdlama** [comment]
That's a really good question.  I imagine there are bits and pieces from your css, some of which are specific to the front page, and others which we want across the site?  It might be good to separate them out if so.  We can have them pulled from the media manager for now and decide/clean/refactor later when it becomes more clear.

Note that I've taken out two css declarations in your css for the front page and put them in the mod_partners module.  We can change that if we need to.  I think again the idea is to use whatever css for the mod_partners module that is general across the site (in case we want to use it elsewhere), and include specific styling when needed.

**Comment by trisketz** [comment]
Sounds good, I'll continue to just upload the css files into the media manager for now.
