### ISSUE TITLE
Padding on community page vs homepage

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#39]
Interestingly enough, the site.css is doing some media queries and putting some padding around the content on the community page. This isn't happening on the homepage. I think for consistency sake, we'll want to have all these pages the same.

**Comment by mdlama** [comment]
Good catch!  I had forgotten about that.  This was taken care of on select pages on the current site by overriding the content pane.  I uploaded a css file that removes the padding, and included it in the community page at the top with this line:

```
{xhub:include type="stylesheet" filename="/app/site/media/css/nocontentpaneopen.css"}
```
