### ISSUE TITLE
Error uploading jpg to media manager

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#45]
I found a stock photo I'd like to try on the resources page from Unsplash. But every time I try to upload it to the media manager, I keep getting this error. 
<img width="563" alt="screen shot 2018-01-25 at 4 49 52 pm" src="https://user-images.githubusercontent.com/21963909/35416787-1e609b32-01f0-11e8-90f1-4a76088bfad1.png">

**Comment by mdlama** [comment]
Can you share the link to the photo here?

**Comment by trisketz** [comment]
I've uploaded it here: [https://qubeshub.org/groups/webdev/File:/uploads/patrick-tomasso-71909.jpg](url)

**Comment by mdlama** [comment]
Well, shoot - I was able to upload it.  :/  Are you able to upload any images to the Media Manager?  I'm wondering if it's because you are not a "super user" but only a lowly administrator.  :)

Also, maybe uploading from a Mac is okay?  I dunno...

**Comment by trisketz** [comment]
hmmm... I have no idea. I just uploaded two pictures just fine. I'm also uploading from a mac. Maybe it was just a fluke last night ¯\_(ツ)_/¯

**Comment by mdlama** [comment]
Might have been.  I say don’t worry about it - we’ve got enough to worry about.  Also, LOVE that unicode emoticon.  :)

- Drew

**Comment by trisketz** [comment]
This is interesting, I sometimes get this error and I sometimes don't. I tried other photos I've downloaded from Unsplash and sometimes I can upload it and sometimes I can't. I can't quite figure out a pattern to it. Here is another file I attempted to upload but couldn't.

[https://qubeshub.org/groups/webdev/File:/uploads/glenn-carstens-peters-203007.jpg](url)

**Comment by mdlama** [comment]
Huh, I was able to upload it from this page:

https://dev.qubeshub.org/administrator/index.php?option=com_media&folder=images

Earlier on my vagrant box I was unable to upload a file that was over 2 MB, even though I upped the limit.  :/
