### ISSUE TITLE
Unable to edit "newhome" in dev administrator

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#48]
I'm not sure what is different, since I was able to make some edits yesterday. But whenever I try to edit the article, it gives me an error. But it's fine when I go edit "community" and "services." The only difference today is that I'm tethering off my phone. I don't know if that would matter though.

<img width="643" alt="screen shot 2018-01-27 at 1 27 34 pm" src="https://user-images.githubusercontent.com/21963909/35475551-1c52dc66-0366-11e8-8d13-2b4a4ecd7221.png">

**Comment by mdlama** [comment]
I had it checked in - can you try again?  Also, did you see an orange lock in front of the page?
