### ISSUE TITLE
[APP/MOD_SHOWCASE] Create billboards module for showcase galleries

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#49]
This module is "working" prototype for billboards.  Future work will have it pulling dynamic content as well.  Not sure if this is the best way to go now that I've started on it (for example, why not have a separate module instance for each item in the grid?), but here we are.

Here's a picture of what it looks like in the community area on the home page:

<img width="730" alt="screen shot 2018-01-27 at 5 54 19 pm" src="https://user-images.githubusercontent.com/4877315/35477233-e625f93a-038c-11e8-8a7d-c510b421cb02.png">

Here's what the HTML looks like

<img width="571" alt="screen shot 2018-01-27 at 6 06 25 pm" src="https://user-images.githubusercontent.com/4877315/35477231-e0843438-038c-11e8-9e6c-8f254a9c8d5a.png">

The module is called "Showcase".  Here's what the settings look like for the instance I am using on the front page:

<img width="1403" alt="screen shot 2018-01-27 at 5 54 49 pm" src="https://user-images.githubusercontent.com/4877315/35477237-04fc2f00-038d-11e8-8a90-0706fefe6a90.png">

Each line in "Item Specification" represents: (1) The number of items, (2) The css class for each item, (3) whether it's static (billboards) or dynamic (publication, groups, etc.), (4) ordered or random, and (5) which billboard collection to pull images from.

Finally, notice that it is requesting images from the Billboard Collection called "Front Page Community" (which has 4 images at the moment).

While not done, I'm putting this here so @trisketz can begin performing the appropriate CSS magic.  @trisketz : let me know what additional HTML you need in there.

**Comment by trisketz** [comment]
Very cool Drew! I have to figure out why it's putting the horizontal image down below in it's own row.  Otherwise, very close!

**Comment by mdlama** [comment]
Forgot to mention - the module will create a container with class "module" by default.  So, what I did was modify your css so that ".community .right" changed to ".community .module-right", and then specify the "-right" in the Module class area in the module settings.  This "Module class" is really a suffix that gets added to the default "module" class.  Hope that works for ya.

**Comment by mdlama** [comment]
@trisketz I think it's time to design the individual grid cells themselves depending on what the content is.  Here's a copy-and-paste of what we wanted in the main Community showcase on the community page from our notes:

- FMN (1) - **Static**
- Featured Groups (1) - **Dynamic**
- Blogs from Partners (1) - **Static**
- Partners (3) - **Dynamic**
- Newsletter (site and Partners) (1) - **Static**
- Workshops and Meetings (1) - **Static**

In the resources, we have publications that we're pulling, and maybe partners with publications that we want to highlight, etc.  It would be good to think about what they look like now, and then at the next UX meeting discuss where we want some of these to link to (for example, partner publications).

**Comment by trisketz** [comment]
@mdlama Does the showcase component allow for pulling of group logos currently? I tried it, and I got an error.

**Comment by mdlama** [comment]
No, only billboards and publications.  I can add that soon.

- Drew

**Comment by mdlama** [comment]
@trisketz I've updated the Showcase module.  Check out the dev site.  Here's what the new item specifications say:

```
1,horizontal,static,indexed,Front Page Community,0
2,regular,static,indexed,Front Page Community,3;2
2,regular,dynamic,recent,groups,featured
1,horizontal,static,indexed,Front Page Community,1
```

The new ordering type is "indexed".  For static billboards, it uses the order index of the billboard within the collection.  

You'll also see that "featured" works as an additional argument to groups.  Featured also works for publications.  Individual publications can be toggled to "featured" by editing their entry on the backend.  For groups, you have to go on the backend to "Users -> Groups", and then click the settings button, then click the "Intro Page" tab.  Here's what you should see:

<img width="786" alt="screen shot 2018-02-02 at 1 55 16 pm" src="https://user-images.githubusercontent.com/4877315/35749996-70d54c6e-0821-11e8-940e-a4a8d46b8c08.png">

Notice the "Featured group list" at the bottom.

I also added some extra classes to the items.  If the item is featured, there is now a "featured" class.  I also added "resource", "group", or "billboard" to the item, depending on the content.

Next steps:

- Allow for the "indexed" ordering type for publications and groups.  For each, use the id of the publication or group to specify it.  This could be another way to "feature" something.  If you need it styled as a featured element, then simply add "featured" manually to the class entry for that item (e.g. "regular featured").
- Right now, dynamic content is sorted by recent.  Do we want to implement random as well?

**Comment by trisketz** [comment]
As of right now, I think random would be a good feature for dynamic featured groups. That way it is on some sort of "rotation." This looks great! I will play around with this. 

Question for you. Does the showcase module pull in titles and author of publications? Does it also pull in group name? Reason I ask was I was playing around with billboards and trying to add a title to an image (as in creating a billboard for a blog post to be featured in the module). It would successfully make that image into a link, but wouldn't actually display any written text in the "learn more" section. I also put some text in the "text" section, but that didn't display anything either. Maybe I'm using it incorrectly.

**Comment by mdlama** [comment]
Okay, just added the header and/or title elements.  I didn't add author for publications as I don't know yet what we want for each type.  Do we want author?  In any case, hopefully the header and title will give you some stuff to work with.  Let me know if you need the html different.  For example, I've got an href around the image and title separately.  Maybe we href the main container?  <shrug>  Not sure...

Quick summary of what is getting displayed:

- Billboards:  Header
- Group: Description (which is just the title basically)
- Publication: Title

**Comment by mdlama** [comment]
Was just thinking as well that rather than adding a featured class, I should add a featured element.  I guess javascript can be used to look for the class and add the element?  Too many options!

**Comment by trisketz** [comment]
I'm thinking we need some sort of... not necessarily a tag, but a header + title for billboards and publications. That way users will know exactly what it is they are looking at. So for example:

- Billboard:
 "Blog/Faculty Mentoring Network" 
"Title"

- Publications
"Resource"
"Title"

I figure groups will be a little more self explanatory and won't need it. Kind of like this mock up. 
<img width="666" alt="screen shot 2018-02-03 at 7 02 26 pm" src="https://user-images.githubusercontent.com/21963909/35773353-eb59737c-0914-11e8-9164-024e1eb03935.png">

**Comment by trisketz** [comment]
I take it back, I see you can add <br> tags in the header of a billboard now. I do think we probably need to add some sort of header for resources though.

**Comment by mdlama** [comment]
Hmmm, I think I'll add an extra element as well for each content type so it can be styled differently.  Lemme think about how to do this - thinking about javascript vs. using the collection name.

**Comment by mdlama** [comment]
Just added the ability to specify a tag to a billboard (with url wanted).  Here's the item specification:

```
1,horizontal,static,indexed,Front Page Community,3,FMN;https://qubeshub.org/groups
```

So, at the end, _after_ an index property (if used), you can put a tag (in this case FMN).  If you want it hyperlinked, use a semicolon (as above) and specify the url.

Whew, this module is getting insane!  Will definitely want to refactor this to something more user-friendly at a later date.

I haven't pushed this yet.  My plan is to push to dev once I've added random capability to groups and publications, and also after adding partners.  Hopefully this will then be 99% done.  I would like to copy some of the css to a css file for this module, which will then be the default styling.  We can then override as needed on pages, and then maybe 100%!!

**Comment by mdlama** [comment]
Oops, forgot about "tagging" dynamic content as well.  I'm going to add an auto-tagging of dynamic content (with proper URLs), and then add a toggle switch "Auto-tag dynamic content?" on the backend for the module.  Then, if a dynamic item has a tag in its specification, it will override the default.

**Comment by trisketz** [comment]
As far as the community section on the front page, I got a little versatility in how we display things as long as we think in a 4 column 2 row grid. So we can mix and match bigs, regulars, and horizontals (I left out verticals because I didn't think it looked good). I need to rework the responsiveness a little bit. But this is how it is looking so far. I'm thinking I'll have to figure something out for anything with really long titles.

<img width="804" alt="screen shot 2018-02-04 at 2 31 19 pm" src="https://user-images.githubusercontent.com/21963909/35782107-e04a9cb4-09b8-11e8-9774-a9765f863b59.png">
<img width="789" alt="screen shot 2018-02-04 at 2 34 16 pm" src="https://user-images.githubusercontent.com/21963909/35782138-28fbd50e-09b9-11e8-9c8e-5f6f0b53470c.png">

**Comment by mdlama** [comment]
That looks great!  I prefer the shading from below only look.  I went ahead and pushed the most recent version to dev.  Here's what the parameters for the module look like now:

<img width="563" alt="screen shot 2018-02-04 at 3 53 10 pm" src="https://user-images.githubusercontent.com/4877315/35782266-8dc27c5e-09c3-11e8-850d-69713ca62f17.png">

So, if auto-tagging is set to `Yes`, then publications or groups will get auto-tagged with "Publication" and "Group", respectively, with each linking to the /publications and /groups area of the Hub.  If you want to override this, just specify a tag like you would for billboards.

Alright, on to allowing for random and indexing for dynamic content, as well as partners...

**Comment by mdlama** [comment]
...and I turned auto-tagging on in the existing showcase module on dev.

**Comment by mdlama** [comment]
Looking so cool!  Just updated the code again on dev.  You can now specify recent, random or indexed for publications and groups.  The index for groups is the group id; similarly, index for publications is publication id.

Gonna add partners tomorrow.  Shouldn't take long as the hard part of the code has been worked out.  Whew!

**Comment by trisketz** [comment]
I'm floating around a couple of ideas when it comes to the tags. 

1. The first is like I have it in the screenshots above - simple white lettering, capitals, and in bold that sits right above the titles. 
2. Second is same styling as above but under the title.
3. And third is to make them actual colored tags - This might be confusing if we are just linking to portal pages though.

I'm also thinking that if we don't want to make these tags look like colored tags and just have them as white text, then I think the tag and title/description might need to be wrapped in a div.

**Comment by trisketz** [comment]
I think I'm leaning towards the tag being above the title/description. I think it looks nice. There is something about the tag off in a corner that looks... abandoned to me. If that makes any sense ;) This example I used two different colors, blue for resources and green for community. But we can do all green if we didn't like the different color idea. 

I also believe I found a nice solution for truncating long titles.
<img width="807" alt="screen shot 2018-02-05 at 5 25 02 pm" src="https://user-images.githubusercontent.com/21963909/35834179-0f3179c6-0a9a-11e8-92e7-b058db3bead2.png">

**Comment by mdlama** [comment]
Hmm, yeah, I see what you mean.  It looks super nice!  Interesting idea on coloring based on Resource/Community, rather than the finer resolution of resources, groups, fmns, blogs, etc.  I kind of like that idea - it matches the menu, and it reinforces the way we want people to filter things.

Also awesome on the line truncation.  It will help to see how this looks with real content!

**Comment by trisketz** [comment]
Ok, I think it's looking good. I added a gradient for groups as well to account for not knowing what their logos might look like (light/no background color vs. dark background color). Might look a little weird with the light/no background colored logos or logos that are wider.. but I figure better safe than sorry. Plus all the blocks will look the same this way. 
<img width="831" alt="screen shot 2018-02-05 at 7 06 22 pm" src="https://user-images.githubusercontent.com/21963909/35836828-1204d0d6-0aa8-11e8-9d19-a090869d6ee9.png">

**Comment by mdlama** [comment]
Woohoo!  Makes sense.  Do you think we need a separator/border between content in case the colors merge?  I'm looking at the two in the bottom-left and thinking they look a little weird.

**Comment by trisketz** [comment]
How does this look?
<img width="831" alt="screen shot 2018-02-05 at 7 14 22 pm" src="https://user-images.githubusercontent.com/21963909/35836989-dae3799e-0aa8-11e8-8c67-4a9882877b79.png">

**Comment by mdlama** [comment]
I don't know.  :)  Can't tell which one I like better.

Also, we could nudge the logos up a bit above the gradient, i.e. not vertically center them.  Thoughts?

**Comment by mdlama** [comment]
Scratch that - I think a separator is good.

**Comment by mdlama** [comment]
Never mind on the nudging, unless you think it would do something interesting.  I think it looks freakin awesome!!!

**Comment by trisketz** [comment]
Yeah, I know what you mean on the nudging. It looked good before I added the gradient in. But if we don't add the gradient, then we might have a problem with the link colors. The problem is, I can either vertically center it or have the image start at the very top of the block and not anywhere in between. Reason being, if someone had a logo that took up the whole height of the block, it would then be pushed down and would just look weird.

**Comment by trisketz** [comment]
One thing, we probably want to change the tag for "publication" to "resource" ;)

**Comment by mdlama** [comment]
Bah!  Stupid publication word.  Just pushed a fix.

Also, I've pushed the most recent version to dev.  I'm going to go ahead and close this thing for now.  This issue is getting rather long - if we have an individual issue or discussion around the showcase module, let's open up a new issue.  

As far as I can tell, the only thing remaining is to add the partner styling.  Awesome work, Jenny!
