### ISSUE TITLE
[TEMPLATES/BMC/SUPER] Fix supergroup template issues

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#69]
For realz...

**Comment by trisketz** [comment]
As someone who is using sass, can confirm.. it is A LOT easier for writing css. That being said, do you want me to stop using sass and switch to less?

**Comment by mdlama** [comment]
No, not necessarily.  I was just beginning to deal with Issue #44 and reminded me of this.  Ilya uses less, and I was thinking of making some modifications myself, so I knew I would need to modify the less to auto-create the css.  Problem is, I can't get some of his less files to "compile".  <shrug>  I'll keep staring at it for a bit.  In regards to your direct question, please don't switch on my account.  :)  Any reason you chose sass over less?

**Comment by trisketz** [comment]
I chose sass because it is the most popular and most used. So it seemed like a natural choice for me. The more I use it the more I realize that I don't think I could go without it ;) On Atom, I installed a plugin called "sass-autocompile." Are you using something similar with Sublime? They probably have one for less.

**Comment by mdlama** [comment]
BTW, just switched back to Atom and loving it.  For some reason I didn't realize it was created by GitHub.  Sweet!

**Comment by mdlama** [comment]
<img width="1425" alt="screen shot 2018-02-13 at 10 22 13 am" src="https://user-images.githubusercontent.com/4877315/36158508-79bf9924-10aa-11e8-81b2-5438904bf39f.png">
<img width="1424" alt="screen shot 2018-02-13 at 10 21 50 am" src="https://user-images.githubusercontent.com/4877315/36158509-79d48cd0-10aa-11e8-9d43-5ddb4709365b.png">
<img width="1421" alt="screen shot 2018-02-13 at 10 21 25 am" src="https://user-images.githubusercontent.com/4877315/36158510-79e471d6-10aa-11e8-945f-ecc5f73f37c5.png">

https://qubeshub.org/support/ticket/1038

**Comment by mdlama** [comment]
Closing this as it is now a duplicate...
