### ISSUE TITLE
Using showcase module on resources portal page

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#74]
@mdlama, I can't tell if maybe I'm going crosseyed or not. But is there anything I need to do different to get the showcase module to work on the resources portal page? I'm pretty sure I wrote the parameters right. But maybe because I'm working under com_resources in the template directory it doesn't follow the same rules?
<img width="681" alt="screen shot 2018-02-10 at 1 52 14 pm" src="https://user-images.githubusercontent.com/21963909/36066111-db605ea4-0e69-11e8-8039-c824fc624bc5.png">

**Comment by mdlama** [comment]
Try this:

```
<jdoc:include type="modules" name="footer" />  
```

I think this is how you include modules within php pages.

**Comment by mdlama** [comment]
P.S. `name` is the same as `position`. 

Here's the info in HubZero Help:  https://help.hubzero.org/documentation/210/webdevs/modules/loading

**Comment by trisketz** [comment]
I should've thought about looking at the documentation. Slipped my mind. This seemed to work:
`<?php
 \Hubzero\Module\Helper::displayModules('resourcesFeature');
   ?>`

**Comment by trisketz** [comment]
Side note for myself - this will not have module container, so you may need to wrap it in a containing div.

**Comment by mdlama** [comment]
Don't worry about not looking at the documentation as it is somewhat incomplete at times.  Did the `jdoc:include` not work?  Regardless, glad you found a solutions!
