### ISSUE TITLE
More spacing on the second nav bar

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#75]
I'm wondering if we should increase the spacing/padding on the second navigation bar. Right now they seem a little close and might look like they run together a bit.
<img width="427" alt="screen shot 2018-02-10 at 1 54 51 pm" src="https://user-images.githubusercontent.com/21963909/36066131-21849b98-0e6a-11e8-83cf-82ff32f0137c.png">

**Comment by mdlama** [comment]
Good point.  I'll pass that along to Ilya...

**Comment by mdlama** [comment]
https://qubeshub.org/support/ticket/1033
