### ISSUE TITLE
Lost media directory again!!!

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#76]
@trisketz Ugh.  So, I updated dev and somehow it cleared the site directory again - only groups is left.  I'm going to make sure to tar/zip the directory before doing anything in the future.  I honestly have no idea what does this.  I'll ask the HubZero team so we can avoid it in the future.  I REALLY hope that it isn't too much hassle to reconstruct things.  I imagine the pain in the butt is all the images and billboards....

**Comment by trisketz** [comment]
@mdlama It's fine, it wasn't too bad honestly since I mostly was working with one billboard to test everything out. All images should be back in.
