### ISSUE TITLE
White text on resource record

### ISSUE THREAD

**Issue by hayleyorndorf** [qubeshub/hubzero-cms#79]
License info and all text in the metrics/social box is white. Selected in image below
![resource record white text](https://user-images.githubusercontent.com/25186673/36105554-e81eb526-0fe2-11e8-9a74-8ba29def34a4.PNG)

**Comment by mdlama** [comment]
Oh, that's why I can't see it!  :)  Good thinking on the highlighting trick.  I have a ticket in for this:

https://qubeshub.org/support/ticket/1032

**Comment by mdlama** [comment]
Added another ticket for good measure :)

https://qubeshub.org/support/ticket/1035
