### ISSUE TITLE
Pictures of people

### ISSUE THREAD

**Issue by hayleyorndorf** [qubeshub/hubzero-cms#81]
More of a question - is it okay to put people's images up here associated with their collection posts? Do we need to ask them first? Also, note that when zooming out to grab this screenshot, the image stayed large. This is on the Resources portal page. 
![resources collections](https://user-images.githubusercontent.com/25186673/36109664-10494894-0fee-11e8-9c38-a933bced0ddf.PNG)

**Comment by mdlama** [comment]
@trisketz I would suggest just cutting off the bottom half of the collection images with their picture, name, and timestamp information.  Jenny, what do you think?  In the future, we can hopefully be pulling from popular collections or something to put here.
