### ISSUE TITLE
Resources vs Publications

### ISSUE THREAD

**Issue by hayleyorndorf** [qubeshub/hubzero-cms#84]
This might be just because we're on dev and I'm unclear of the current differences between dev, stage, and production. Also not sure about what will automatically be changed or what is an issue. So feel free to ignore any issue I post that is irrelevant. 

Anyway - when on the Resources portal page - there's no button to submit a resource which I think is okay because it is in the secondary menu. When that is developed, will it take you to the Publication submission but everything will say Resource? 

When on the Software page, there's a "submit a resource" button. And it takes you to the old Resource submission process. Does this system have to remain up for software? If so, can we change the name to "Submit Software"?

**Comment by mdlama** [comment]
Unfortunately Resources has to remain up for the tools submission.  We can change the language, though.  Thanks for finding that - I haven't put my attention on secondary pages yet.  I've been focusing on components, like groups, projects, etc.

**Comment by mdlama** [comment]
Also, regarding everything saying Resource, it is going to be a little challenging, I think, this smoke-and-mirrors trick where we hide "publications" everywhere.  There is a language file where I can change all instances of "publications" or "Publications" to some version of resources rather quickly, but it looks like the word Publication is hard coded in multiple places that I'll have to manually hunt down.  Not to mention the issue with urls and breadcrumbs.  I'll investigate this week...

**Comment by mdlama** [comment]
See Ticket #94
