### ISSUE TITLE
Modify default template for full record view

### ISSUE THREAD

**Issue by mdlama** [qubeshub/hubzero-cms#87]

**Comment by ssdonova** [comment]
make sure that the template checks for the publication master type - so that we can have different ones.

**Comment by trisketz** [comment]
I have a basic template up here: [https://dev.qubeshub.org/groups/webdev/pubrecord](url).
Still some stylings that needs to happen and not responsive yet. I also took out some content menu items and combined a couple, which can always be changed. 

Main thing right now is I'm not sure how to get ajax going on this right now. That will take me a little time, which I'm happy to do now. Or if you'd rather I work on other things and come back to it, I can do that as well.

**Comment by trisketz** [comment]
p.s. I know you said to make an article page, but I kept getting errors whenever I'd try to make a new one. So that is why it's under webdev again ;)

**Comment by mdlama** [comment]
Looks great.  I'd hold off on AJAX at the moment.  Let me ping the HubZero support community and see what they say.  We might already have some built in stuff to help us here.

**Comment by trisketz** [comment]
Question for you guys. For sharing publications to social media outlets, do you want all the same ones as we have currently or shave it off a bit? I'm mainly thinking of the LinkedIn and Delicious one. (I've actually never heard of Delicious).
<img width="217" alt="screen shot 2018-02-21 at 6 26 37 pm" src="https://user-images.githubusercontent.com/21963909/36513408-16154482-1735-11e8-8a43-b110447f4128.png">

**Comment by ssdonova** [comment]
What! When were you born? Delicious was an awesome social bookmarking tool - emphasis on the **was**.

**Comment by mdlama** [comment]
Hmmm, might be good to revisit these and make sure we are up-to-date.  Where's Snapchat!!!?!?!  :)

**Comment by mdlama** [comment]
Hi, folks.  Jenny, I've been looking at the AJAX on the Hub.  Here's one file (discussions in courses) that uses AJAX with Plugins:

https://github.com/qubeshub/hubzero-cms/blob/master/core/plugins/courses/discussions/assets/js/discussions.js

...and another that uses AJAX with the API:

https://github.com/qubeshub/hubzero-cms/blob/master/core/plugins/courses/outline/assets/js/build.js

I'm still not sure we need to use AJAX for the tabs.  Let me look at the way the admin interface does tabs - that may be easier.

**Comment by trisketz** [comment]
I think my main concern and thinking of using ajax, is that the page won't reload when you hit the tabs on the publication record views. And also, if you hit the back button on the browser, it won't go back to the previous tab, but instead to the previous page you were on. Unless there is another way around this that I'm not thinking of.

**Comment by mdlama** [comment]
Creating an entirely self-contained project for this todo:  https://github.com/orgs/qubeshub/projects/4
