### ISSUE TITLE
[Showcase module] Entire image is not clickable

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#95]
@mdlama You were right, the overlay was preventing the entire image from being clickable. There is one solution that would be (hopefully?) easy. Would it be possible to change the html structure a bit? The `<a>` anchor would wrap the entire resource/billboard-img div? For example:

```
<div class="resource/billboard">
  <a href="/url>
    <div class="resource-img/billboard-img">
      <img src="/url">
    </div>
  </a>
</div>
```

If not, then I can think of something else :)

**Comment by mdlama** [comment]
Sure!  I need to pick up the kids now, but can get back to this later this evening.  Hope that's okay!

**Comment by trisketz** [comment]
Awesome! Thanks!

**Comment by mdlama** [comment]
I pushed the changes to dev.  I also did something similar for tags to make the entire tag clickable and not just the text.

**Comment by trisketz** [comment]
I see that, I think it looks good. Thanks!
