### ISSUE TITLE
News & Activities

### ISSUE THREAD

**Issue by trisketz** [qubeshub/hubzero-cms#98]
Friendly reminder that we also have a news & activities link on the upper right of the template. 

Also, as of right now, I made the page one big showcase/feature. If you rather have me break it up into sections, let me know.

**Comment by mdlama** [comment]
Awesome, thanks for the reminder.  I actually have a lot of template fixes coming to dev soon.  I'll alert you after pulling code in.

**Comment by mdlama** [comment]
Good lord.  We lost the media directory again.  Sorry!  I've just pushed the changes.
